# Generated by Django 3.0.8 on 2022-03-10 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_systemuser_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemuser',
            name='is_profile_completed',
        ),
    ]
