# Generated by Django 3.0.8 on 2022-03-13 21:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_systemuser_is_profile_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='completedcourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='completedcourse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.RemoveField(
            model_name='lastvisit',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='lastvisit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='level',
            name='course',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='level',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='user',
        ),
        migrations.RemoveField(
            model_name='unlockedlevel',
            name='level',
        ),
        migrations.RemoveField(
            model_name='unlockedlevel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='unlockedmission',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='unlockedmission',
            name='user',
        ),
        migrations.RemoveField(
            model_name='video',
            name='mission',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='CompletedCourse',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='LastVisit',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.DeleteModel(
            name='Mission',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='Trial',
        ),
        migrations.DeleteModel(
            name='UnlockedLevel',
        ),
        migrations.DeleteModel(
            name='UnlockedMission',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AddField(
            model_name='exercise',
            name='msucle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Muscle'),
        ),
    ]
