# Generated by Django 3.0.8 on 2022-03-13 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20220314_0244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='msucle',
            new_name='muscle',
        ),
    ]
