# Generated by Django 3.0.8 on 2022-03-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20220316_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='max_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='max_value_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
