# Generated by Django 3.2.8 on 2022-03-17 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20220316_1235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ('-max_value',)},
        ),
    ]
