# Generated by Django 3.2.8 on 2022-03-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_group_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='icon',
            field=models.CharField(default='avatars/default-profile.png', max_length=150),
        ),
    ]
