# Generated by Django 3.2.8 on 2022-03-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20220317_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='icon',
            field=models.CharField(default='/media/avatars/default-profile.png', max_length=150),
        ),
    ]
