# Generated by Django 3.2.8 on 2022-03-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_group_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='avatar',
            field=models.CharField(blank=True, default='avatars/default-profile.png', max_length=255, null=True),
        ),
    ]
