# Generated by Django 3.2.8 on 2022-03-28 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_acheivement_badge_goalcounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalcounter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.systemuser'),
        ),
    ]
