# Generated by Django 3.2.8 on 2022-03-28 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_acheivement_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acheivement',
            name='image',
        ),
        migrations.RemoveField(
            model_name='acheivement',
            name='name',
        ),
    ]
