# Generated by Django 3.2.8 on 2022-04-07 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20220407_1649'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Value',
            new_name='SValue',
        ),
    ]
