# Generated by Django 3.2.8 on 2022-04-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_rename_value_svalue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ('-weight',)},
        ),
        migrations.RemoveField(
            model_name='goal',
            name='reps',
        ),
        migrations.AddField(
            model_name='goal',
            name='weight',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
